include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
