name: cine_parker
description: "Cine Parker is a movie app that allows you to browse and log your favorite movies."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  dynamic_color: 1.7.0
  equatable: ^2.0.7
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  get_it: ^8.2.0
  go_router: ^13.2.4
  google_fonts: ^6.3.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  very_good_infinite_list: ^0.7.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - .env